---
x_api_token: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          34323566396565366437666462353630646466636262396463646332383437633437306465323763
          6539343337343333303666663139663862633337356432360a626166303335656534326637633533
          61643065636531353765373236376262306539623433623234353234636537376564343265366531
          3235386639313137330a313762303833636630653239363238306235643038353432623136393230
          31306430343566636463306239633265323435346561383765393531633739366634306165336562
          61376230383965383730626266343637353761643636313133313563656562643865343030633537
          62626533666131646633333265326632313766326165343230383463316136373135623633326164
          62333464393038373231
x_linode_tag: Demo-MaC
x_linode_region: ca-central
x_ssh_auth_key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC0hUWtb6rMqB4mB1DnNNv9XxGLSE5V7Rgy/Ms4BpOX0nH5+6yzS1GrltBJ1+SOfPUWYCK23ynxUCRT2PPbF0P1RAFYHOsSCvhoDYBU3l/VWvYr/tezqkCP+qRKEBcp5GnoefB6Whvt9QwnmtulCyv+dQQUB4Bz/yj29kBoEntZT2Gv9r8Ang+hn1BpT/ngFbRDGSFmPG6GZBunEl0C0poHkD2ZgUGaKXuvgUaFpDhkUuq10Uhp+zKZN/nBnKHL7Gfi+zPzmyFYqeE2SNgHy5V6sBlJ+B42OJ9vvdvDuyBY/0Q9YQEx1cjqE17XAUuzprC2BPmM4qxEmKpFuA+/Rp/VKlnEviKBqt68dFkHJPT9GomL4YS2w507HIRBTPfF2gDtcig+yZCFYPVFFp4Xxaxo0POQS/aTXXX0JURiu6iWgE0rznuyi2YZ955gu3m43977yoREZY04OgFmYzDM31gE6gTIqoEGTwhEjGX+OY+DKmT0n+UH5SukHj3YMctSlYs= ey@ls1"
zabbix_agent2: true
zabbix_agent2_server: "{{ x_zabbix_server_ip }}"
x_zabbix_username: Admin
x_zabbix_password: zabbix
ansible_httpapi_port: 80
ansible_httpapi_pass: "{{ x_zabbix_password }}"
x_templates: []
x_custom_templates_files: []
